[package]
name = "pusher-credentials"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
hex = "0.4.3"
hmac = "0.11.0"
sha2 = "0.9.8"

